matrix:
 include:
  - os: linux
    dist: trusty
    addons:
     apt:
      sources:
       - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty universe"
      packages:
       - ocl-icd-opencl-dev

  - os: osx

language: c
compiler:
 - gcc
 - clang

script: make && ./clinfo
